[package]
name = "Problem_permutation"
version = "0.1.0"
edition = "2018"

[dependencies]
permutate = "0.3.2"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

